AllCops:
  Exclude:
    - vendor/**/*
    - log/**/*
    - db/schema.rb
    - bin/*
    - test/support/action_cable/*

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
